export type Faculty = {
  id: string;
  label: string;
  shortLabel: string;
  programs: string[];
};

export const FACULTIES: Faculty[] = [
  {
    id: "applied-science",
    label: "The Faculty of Applied Science",
    shortLabel: "Applied Science",
    programs: [
      "Biomedical Engineering",
      "Chemical and Biological Engineering",
      "Chemical Engineering",
      "Civil Engineering",
      "Computer Engineering",
      "Electrical Engineering",
      "Engineering Physics",
      "Environmental Engineering",
      "Geological Engineering",
      "Integrated Engineering",
      "Manufacturing Engineering",
      "Materials Engineering",
      "Mechanical Engineering",
      "Mining Engineering",
    ],
  },
  {
    id: "arts",
    label: "The Faculty of Arts",
    shortLabel: "Arts",
    programs: [
      "African Studies",
      "Anthropological Archaeology",
      "Anthropology",
      "Art History",
      "Asian Language and Culture",
      "Asian Area Studies",
      "Canadian Studies",
      "Classical and Near Eastern Archaeology",
      "Classical Studies",
      "Cognitive Systems (BA)",
      "Comparative Literature",
      "Computer Science (BA)",
      "Creative Writing",
      "Critical and Curatorial Studies",
      "Economics",
      "English",
      "Environmental Geography",
      "European Studies",
      "First Nations and Indigenous Studies",
      "French",
      "Gender, Race, Sexuality and Social Justice",
      "Geography",
      "Germanic Studies",
      "History",
      "International Relations",
      "Italian Studies",
      "Japanese Language and Culture",
      "Korean Language and Culture",
      "Latin American Studies",
      "Linguistics",
      "Mathematics (BA)",
      "Medieval Studies",
      "Modern European Studies",
      "Music",
      "Philosophy",
      "Philosophy, Politics and Economics (PPE)",
      "Political Science",
      "Psychology",
      "Religion, Literature and the Arts",
      "Romance Languages",
      "Russian",
      "Sociology",
      "Spanish",
      "Speech Sciences",
      "Studio Arts",
      "Theatre",
      "Visual Art",
      "World Literatures",
    ],
  },
  {
    id: "commerce",
    label: "The Faculty of Commerce and Business Administration",
    shortLabel: "Commerce",
    programs: [
      "Accounting",
      "Finance",
      "Marketing",
      "Management Information Systems",
      "Operations and Logistics",
      "Organizational Behavior and Human Resources",
      "Business Technology Management",
      "International Business",
    ],
  },
  {
    id: "forestry",
    label: "The Faculty of Forestry and Environmental Stewardship",
    shortLabel: "Forestry",
    programs: [
      "Bioeconomy Sciences and Technology",
      "Conservation",
      "Forest Management",
      "Forest Operations",
      "Forest Sciences",
      "Wood Products",
      "Urban Forestry",
      "Indigenous Land Stewardship",
    ],
  },
  {
    id: "land-food",
    label: "The Faculty of Land and Food Systems",
    shortLabel: "Land & Food Systems",
    programs: [
      "Applied Animal Biology",
      "Sustainable Agriculture and Environment",
      "Dietetics",
      "Food Science",
      "Nutritional Sciences",
      "Food, Nutrition, and Health",
      "Food and Resource Economics",
      "Global Resource Systems",
    ],
  },
  {
    id: "science",
    label: "The Faculty of Science",
    shortLabel: "Science",
    programs: [
      "Atmospheric Science",
      "Astronomy",
      "Biochemistry",
      "Biology",
      "Cellular, Anatomical, and Physiological Sciences",
      "Chemistry",
      "Cognitive Systems",
      "Combined Major in Science",
      "Computer Science",
      "Data Science",
      "Earth and Ocean Sciences",
      "Environmental Sciences",
      "Geographical Sciences",
      "Geological Sciences",
      "Geophysics",
      "Integrated Sciences",
      "Mathematics",
      "Mathematics and Economics",
      "Microbiology and Immunology",
      "Neuroscience",
      "Oceanography",
      "Pharmacology",
      "Physics",
      "Statistics",
    ],
  },
];

export const FACULTY_ICONS: Record<string, string> = {
  "applied-science": "⚙️",
  "arts": "🎭",
  "commerce": "📊",
  "forestry": "🌲",
  "land-food": "🌱",
  "science": "🔬",
};
